2021 07 07 capability readme
Azure/opendigitaltwins-building pull request #48
Opened 2021-07-07 19:50 UTC by rszcodronski

Adding a ReadME for Capabilities to capture the work completed around modeling and tagging.

Note - I have also added several properties which are described at the end of the Readme regarding "values" metadata.

Is it okay to leave "unit" as a String for now or should this be and enum of all the possible units that exist in the DTDL Semantic Types or defined elsewhere?

2021-07-08 23:58 UTC, alinamstanciu approved these changes
How would people find the readme.md in capability folder?
We need a phrase in the main doc which links to this readme, otherwise it's hard to find it.
Could you please add that phrase? Thanks

2021-07-09 14:13 UTC, hammar requested changes
Great text, good work Rick! I added a couple of minor spelling issues that you may want to fix, but overall, this looks good to me. Very useful for implementors, I'm sure.

1. I'd suggest placing this file outside of the Ontology directory; to avoid the risk of it being overwritten by automated tools (e.g., the translation mechanism).
2. I'd also suggest not including the updated properties in the same PR, since we've already reviewed the other PR for those, and I think a little more work is needed on them.

2021-07-09 14:13 UTC, hammar commented on Ontology/Capability/README.md
> +## Capabiltiy Models
Capabiltiy -> Capability

2021-07-09 14:13 UTC, hammar commented on Ontology/Capability/README.md
> +This guide will provide an understanding of how to become familiar with the capabiltiy data model, define capabilty twins and recommendations for how to best use the ontology.
capabiltiy  -> capability
capabilty -> capability

2021-07-09 14:13 UTC, hammar commented on Ontology/Capability/README.md
> +The Capability models maintain several **properties** which allow additional metadata on the twin to provide context to 1) classificaiton 2) values and 3) communication configuration. The properties
classificaiton -> classification

2021-07-09 14:13 UTC, hammar commented on Ontology/Capability/README.md
> +The Capabiltiy models described above provide a great means of classifying based on **function** and **kind** which brings consistency and inheritence to these two common means by which a Capability
Capabiltiy -> Capability

2021-07-12 23:51 UTC, closed without merging